### ISSUE TITLE
[python] Impossible test cases

### ISSUE THREAD

**Issue by SpaceLenore** [dbwebb-se/matmod#38]
## Impossible test cases in matmod/material/exercises02py/exercises02tests.py 
the cumulative_binomial is expected to spit out 2 different values based on the same input variables.
`test_cumulative_binomial1` and `test_cumulative_binomial2` both run `f.cumulative_bin(150, 200, 0.75)` but expect different values. That is impossible.

**Comment by henrikfredriksson** [comment]
The test files are updated

Thanks for pointing this out
